### ISSUE TITLE
Windows Smartscreen Warning

### ISSUE THREAD

**Issue by stlorenz** [emoacht/Monitorian#139]
When I try to install the msi, I get a Windows Defender Smartscreen warning. 
I can override it, but I think there should be at least a waring in the Repo to not scare a user. 

Windows 10 20H2 Insider

**Comment by emoacht** [comment]
Hello, there are short answer and long answer.

__Short answer:__ Use Microsoft Store version as written in Download section.

__Long answer:__ It often happens to an app which is not digitally signed. As far as l know, a developer has to use code signing service of code signing companies and it would be cumbersome and costly. It is one of reasons why I release this app in the Store where such certification is provided the Store. Anyways, I am not responsible for the behaviors of security software and even if I add some explanation on them, it will be useless because if people believe the waring of those software, they will not believe my comments.
