### ISSUE TITLE
Feature Request - Adaptive brightness control for external monitor

### ISSUE THREAD

**Issue by IUmplt** [emoacht/Monitorian#246]
I have seen previous request on using surface's ambient light sensor to control the brightness of the external monitor. The problem you mentioned is that the adaptive light curve would be different. I think this software Lunar (has exactly the function we would like to have for Mac) https://github.com/alin23/Lunar provides a great solution to this. You can let users to set a brightness/contrast curve on their own and use the brightness of the laptop monitor to find a point on the curve.

I think this can be a very useful feature and probably the codes for Lunar would be helpful.

**Comment by emoacht** [comment]
To be clear, I have no incentive to implement it on my own.

**Comment by IUmplt** [comment]
Ok, I think for now it may be helpful if you can leave this request open and probably write a notice on the home page to see if there is anyone who would like to help implement this feature. I think this is a feature desired by many and there may be some people who would like to help.

I will try to work on this and contact the author of Lunar if I have time during the winter holiday.

**Comment by jacob-pro** [comment]
Just putting this here in case it can provide any help or inspiration:

I have a vaguely similar project here
https://github.com/jacob-pro/solar-screen-brightness
which implements adaptive brightness based on sunrise and sunset times

**Comment by emoacht** [comment]
@IUmplt Why don't you fork and work on your own repository and ask others to help from that repository? It is the way how GitHub works.

**Comment by IUmplt** [comment]
I do not understand. We are trying to add a feature on an existing app published on the Microsoft store. If I fork the repo and do this, how can I publish this feature to the Microsoft store? Or do you give me the permission to use your code and publish another app?

**Comment by jacob-pro** [comment]
@IUmplt  This obviously isn't my project, but here is some advice:

1. This is an MIT licensed project (see the LICENSE file), which is permissive - so we are allowed to do whatever we want with the code, including putting it in another app.
2. If you make a fork on GitHub (using the button) it will track that it is a fork so that any users viewing it can see the upstream project it originated from.
3. Creating a fork is part of the typical GitHub workflow for contributing to a project that isn't your own - i.e. it is being suggested that you create a fork and implement the code with your desired feature. You can then create a pull request to merge code from your fork into this repo, which I'm sure the maintainers would welcome.
4. If you would like to collaborate with others when writing this feature you can do it by accepting PRs to your fork (or granting trusted contributors access directly to your repo).
5. This is a free and open source project maintained by volunteers, it is usually reasonable to submit a feature request, but there should be no expectation that it will be carried out, unless you go and write the code yourself and submit a PR.

**Comment by IUmplt** [comment]
@jacob-pro
Thank you very much for your comments. I understand that it is good to work on my own repo when trying to implement this code, and request to merge when I finish. I will do that when I start to work on it.

What I do not understand is that why I should ask others' help at this stage on my own repo. As you said that users can view the upstream, but few will come to my forked version from this upstream. It will be very helpful if the maintainer can put a link to my repo in this case.

I am currently unsure about the maintainer's idea on whether this feature should be incorporated to the existing app. I can try to gather help on my own, but if the eventual goal is to contribute to this project, it is kind of strange. Probably I misunderstand the maintainer's meaning and I am sorry for that if it is the case.

**Comment by magcode** [comment]
Slightly off topic ... I have a mqtt based light sensor in my room.
I've created a little program which automates the brightness setting based on the sensor value: [mbri](https://github.com/magcode/mqtt-tools/tree/master/mbri)

**Comment by emoacht** [comment]
I am closing this issue.
