### ISSUE TITLE
Icon won't remain in taskbar position after updates.

### ISSUE THREAD

**Issue by DrRZ** [emoacht/Monitorian#267]
By default, at least on Windows 10, the Monitorian icon appears to get moved to the overflow section of the taskbar tray area (where you need to click the carat/up-arrow to get to it). That's fine and I move it out of that area to the taskbar so it's always visible for quick access to it.

After every update from the Microsoft Store, it gets moved back to the overflow area and I have to move it back again. 

I have no idea if there's anything that can be done by the application to prevent this behavior or if it's a Windows behavior that can't be changed. It's obviously a very minor annoyance. But if there's something easy that can be added to the app to prevent this it would be really nice.

Thanks.

**Comment by emoacht** [comment]
Thanks for the suggestion.
Probably it is because each version of this app would be recognized as different app by the OS in terms of management of taskbar. Probably it is related to the placement of executables files but unfotunately, it is not controllable by a developper.

That said, to intervene in this behavior, you need to hack somehow the data managed by the OS while there is neither official documentation on the data structure nor assurance that it would remain unchanged version to version of the OS.

Therefore, I would say, it goes beyond what a developper can do.
