### ISSUE TITLE
External screen handle get invalid after sleep

### ISSUE THREAD

**Issue by WangLeto** [emoacht/Monitorian#28]
After I sleep my computer and reboot, the external screen (Ddc Monitor) disappeared. Maybe add a button to allow redetecting screens manually.

**Comment by emoacht** [comment]
I am aware that it may happen sometimes after resume. I think it is caused by APIs that do not respond correctly immediately after resume. BTW, have you ever seen any particular exception as you wrote in the title?
Allowing a user to manually trigger rescan would be one solution. I am wondering how such function could be naturally integrated into existing UI though.

**Comment by WangLeto** [comment]
I think maybe it is because after long time sleeping and then resume, the monitor handles are reallocate, so the original ones become invalid.
Not other problems found yet.
Good job by the way.

**Comment by emoacht** [comment]
I see. Actually, the function in this app to add/remove monitor entries does not depend on the monitor handle regardless of its validity after resume.
I was thinking about this issue but adding the function to trigger rescan seems not the best solution because a user should not be bothered in the first place. Instead, I would make longer the interval for automatic rescan after resume. In your observation, how long does your monitor need to be correctly scanned after resume?

**Comment by WangLeto** [comment]
The truth is, usually after I resume my computer I would immediately adjust the screen brightness. In addition, I notice there is a [event fired](https://stackoverflow.com/questions/228288/how-can-i-know-when-windows-is-going-into-out-of-sleep-or-hibernate-mode) sent when computer resume from sleep, which you may use to trigger a rescan.

**Comment by emoacht** [comment]
The current version already calls the APIs two times, 3 seconds and around 10 seconds immediately after resume event fires. The problem is, some APIs may not return correct information at those timings probably because the system is too busy for resuming.

**Comment by WangLeto** [comment]
It's hard to reproduce the bug... so I have no good suggestions. 😂

**Comment by emoacht** [comment]
It's okay. Released Ver 1.9.0.
