### ISSUE TITLE
Feature request - Time scheduled control

### ISSUE THREAD

**Issue by GitStudying** [emoacht/Monitorian#290]
I am currently mostly using Clickmonitor DDC, in this application a schedule can be created easily where you can set a time of day.
Are you open to anything like this?
I would switch instantly to Monitorian as my monitor manager because of the better design and usability!

**Comment by emoacht** [comment]
Thanks for the explanation.
Task Scheduler looks complex because of its versatility but I think it is a matter of getting used to it.
I would not say your suggestion is impossible but it can be done without this app. This app is designed to open for communication with other app through command-line and so scheduling is not necessarily done by this app.

**Comment by ClementParis016** [comment]
Hi @emoacht, jumping up on this one and saw there are[ a few other closed issues for this](https://github.com/emoacht/Monitorian/issues?q=is%3Aissue+schedule+is%3Aclosed).

I think there are a bunch of people (me included) who would love having basic scheduling settings as part of this app, rather than having to set those manually with Task Scheduler. I think lots of users are waiting for this, because currently this app is the tool that looks to be the most capable of such thing.

I understand the design philosophy of keeping this simple and leveraging existing scheduling tools that are great at doing this one job, but from a user perspective it's not practical.

Apart from the philosophy, I'm pretty sure you could make it a paid add-on that people would be happy to pay a fair price for. Or maybe even crowdfund the development of the feature.

Such a feature would make this humble app as much of an essential as [Lunar ](https://lunar.fyi/)is on macOS 🙏🏻
