### ISSUE TITLE
System.Management.ManagementException occurs when starting Monitorian

### ISSUE THREAD

**Issue by ikrase** [emoacht/Monitorian#296]
After using monitorian for a while, I have started having trouble with it initially having some error dialog boxes (with the option to write exception log, attached), and then after that, simply hanging. As far as I know, nothing has changed on my PC. 

When Monitorian is started there will be just a window with nothing but the title, then I can open either the left-click menu or the brightness slider, but nothing responds to clicks and there is an hourglass cursor when mousing over. 

I created an operation log (manually edited settings file to enable this). Clean reinstall did nothing. 
[operation20220227.log](https://github.com/emoacht/Monitorian/files/8148477/operation20220227.log)

[exception.log](https://github.com/emoacht/Monitorian/files/8148475/exception.log)

I have confirmed using a different tool that DDC/CI is working fine.

**Comment by emoacht** [comment]
Thanks for the report.
This exception is caused by WMI function of the OS. In most cases, it works fine but sometimes it doesn't by unknown reasons.
There is nothing an app can do to prevent it but just ignore it.
WMI is essential to track the change of internal monitor but not necessary for external ones. Then, what monitors does your system has except HP's one which appears in operation.log?

**Comment by ikrase** [comment]
I don't have any monitors other than the single external HP monitor.

I do see that my monitor is listed as a Generic PnP Monitor in Device
Manager but I do not know if this is normal or not. I then tried installing
an optional Windows Driver Update that gave it a vendor specific name.
(installed OEM114.inf). Monitorian still did not work.

Might restarting the WMI service help? Or to disable Monitorian's use of
WMI somehow?

**Comment by emoacht** [comment]
Thanks for the information.
As the fundamental function of the OS, WMI should not fail but actually, it does. Too bad.
I am wondering if this kind of exceptions happen, whether we should regard all WMI functions are unreliable or not. If so, probably all WMI related functions of this app should be stopped for consistency.

**Comment by ikrase** [comment]
Is there a way to configure the app to turn off WMI functions?

**Comment by emoacht** [comment]
No. In fact, WMI is used for a variety of purposes and so it is not easy to tell which part of WMI functionality is reliable and which is not.

**Comment by emoacht** [comment]
Let me recap this issue.

__Description:__ Sometimes an error occurs when starting this app and it is inevitably closed. It is because `System.Management.ManagementException` is thrown when this app starts watching brightness changed events by WMI. This WMI event is a part of the OS and known to fail sometimes for unknown reasons. It is critical to track the bightness changes of internal monitors but not necessary for external monitors.

__Solution:__ This WMI event (WmiMonitorBrightnessEvent) is a member of `MSMonitorClass` class and other members of this class are used to get/set the brightness of internal monitors by WMI. If this error occurs, it will strongly suggest that we cannot reliably use those other members as well. Therefore, this app is changed to catch this error and disable WMI functions for internal monitors so that it will be able to work only for external monitors.

This change is applied by 2ef0632c419ae92da6778e8a22de3a06fea35be3
