### ISSUE TITLE
After update, previous configuration is lost

### ISSUE THREAD

**Issue by rudolphos** [emoacht/Monitorian#368]
Brightness settings remain, but UI settings are lost, like 'enable changing brightness in unison' and their configuration.
Windows 10, 64bit

**Comment by emoacht** [comment]
The update will not guarantee the previous settings to be kept.

**Comment by emoacht** [comment]
The root cause of this issue came from Microsoft Store system where all files that had been created by app at the location which  is managed by the Store system will be deleted on uninstallation. Whether the settings file at that location survives during the update process is unknown.
To ensure the settings file to be kept intact during the udapte process, it needs to be stored somewhere out of control of Microsoft Store system. That means such file remain even after uinstallation of app.
Thus, this issue depens on whether users can be tolarate such possible gabage file.

**Comment by emoacht** [comment]
In fact, some apps store thier own files in MyDocuments. Although MyDocuments is the place where an app can freely write or read files other than AppData, I don't think it is nice because the place is primarily for user files.

Therefore, I decided to store the settings file in Temp. Temp is not completely safe place to store a file, perhaps no one will care about a file there. This is implemented as of Ver 3.15.
