### ISSUE TITLE
Not all monitors get dectected.

### ISSUE THREAD

**Issue by robtoll** [emoacht/Monitorian#452]
The first thing to say is that not very often, but sometimes all 4 of my monitors are successfully detected!
So I know it's not a technical issue about my monitors being incompatible...

Mostly it will detect 2 or 3, but rarely 4 first time. Tripple clicking the "Monitorian" in the systray menu reveals additional tools such as rescan monitors, but this doesn't seem to work either.  You can click the rescan button once or twice or many times and it's unclear if anything is happening at all.

It failed to detect all 4 monitors about 10 times in a row, which makes it pretty unusable for me.

The strange thing about it is that it usually picks up 3 monitors. The monitor that it usually doesn't discover is identical to one of the ones that it always picks up.

I'm up to date with the latest version. I know this isn't an easy app to make. I'm going to fall back to my previous app called pango bright, which is not anywhere near as good, but it does work consistently.

Any improvements to this apps detection functionality are be keenly awaited.

Thanks

**Comment by emoacht** [comment]
Thank you for reporting.
This app checks not only the existence of a monitor but also the controllability of each monitor when it searches monitors. Some of your monitors might fail to respond to the inquiry from this app time to time.

To check what is happening, could you post probe.log and operation.log desscribed in [Reporting](https://github.com/emoacht/Monitorian#reporting)?

**Comment by ryankhart** [comment]
> Thank you for reporting. This app checks not only the existence of a monitor but also the controllability of each monitor when it searches monitors. Some of your monitors might fail to respond to the inquiry from this app time to time.
> 
> To check what is happening, could you post probe.log and operation.log desscribed in [Reporting](https://github.com/emoacht/Monitorian#reporting)?

Ya, I'd like to report an issue with my monitor not working with this app, but I have no idea where to find my probe.log and operation.log files. Could some more detailed instructions be added to the README, maybe?

**Comment by emoacht** [comment]
@ryankhart Could you read [Detection of external monitors](https://github.com/emoacht/Monitorian#detection-of-external-monitors) and [Reporting](https://github.com/emoacht/Monitorian#reporting) in readme?

**Comment by emoacht** [comment]
@ryankhart If you read [Reporting](https://github.com/emoacht/Monitorian#reporting) in README and still you cannot understand how to report with the logs, I am afraid to say but it is hard for you to make a meaningfull report.

**Comment by ryankhart** [comment]
@emoacht, after doing a second pass through the README, I realized that all the required information was there, but it was presented in the opposite order of what I needed, with some steps missing or unclear.

> Probe
You can check the compatibility of your monitor by probe.log. It will include raw information on monitors, including capabilities through DDC/CI, from various APIs that are used to find accessible monitors. To get this log, tap Probe into monitors in the hidden menu described below.
To open the hidden menu, click app title at the top of menu window 3 times.

I wouldn't refer to it as a "menu window" since a window doesn't disappear when you click away from it. It's actually a context menu that appears when you right-click. This part of the README has been the most puzzling for me. It led me to feel discouraged as I assumed that I needed some specific information or access to an outside resource that wasn't clarified in this document.

Here is how I would have written it coming from the perspective of a fresh pair of eyes:

### Probe
First, you must generate a probe.log file using the following steps:
1. Right-click on the Monitorian icon in the system tray. (not left click)
2. Click 3 times on the title bar where it says `Monitorian` to access the hidden menu.
3. Click on `Probe into Monitors`.
4. When the dialogue box for "Save probe log to Desktop?" appears, click OK.

With this probe.log file, you can check the compatibility of your monitor. It will include raw information on monitors, including capabilities through DDC/CI, from various APIs that are used to find accessible monitors. Include this file in your reporting.

### Operations
As part of testing, you can set this app to record operations to scan monitors and reflect their states. To enable the recording, do the following steps:
1. Right-click on the Monitorian icon in the system tray.
2. Click 3 times on the title bar where it says `Monitorian` to access the hidden menu.
3. Click to check `Make operation log`.
4. After some information is recorded, you will be able to copy __operation.log__ by `Copy operation log`.

If you notice an issue, <ins>enable the recording and then wait until the issue happens. When you notice the issue again, copy this log and check the information including the change before and after the issue.</ins> Include this file in your reporting.

**Comment by ryankhart** [comment]
Oh, by the way, in the process of starting up Monitorian again to test this out, it seems to be working as intended now. I wonder if restarting my PC after the installation was what did it. Regardless, it's working now, so I may not need to report anything unless it stops working later.
