### ISSUE TITLE
Brightness per user

### ISSUE THREAD

**Issue by BartTK** [emoacht/Monitorian#480]
My PC has multiple user accounts. When one user adjusts the brightness using Monitorian, this affects all users of the system. In my case this is not desirable. One of the users prefers a low brightness to reduce eye strain, while the other users prefer the regular brightness. To restore regular brightness, the other users must now also install Monitorian to be able to set brightness back to a normal level. 

I would prefer that Monitorian does not affect other users than the one that installed, and is using, Monitorian. Would it be possible to store the brightness per user and only apply it only when that user is using the system?

So do something like this:
- When a user logs in to the system, or when that user is switched to using fast user switching,
1. Backup current brightness level
2. Apply the previous brightness level for this specific user
- When a user logs out, locks the system, or when fast-switching to another user,
1. Apply the original brightness level that was backed up.

**Comment by emoacht** [comment]
The brightness setting is stored in a monitor itself and natually affects all users who use the same monitor.
I think basically you can accomplish what you want by "Restore brightness on reconnection" of Microsoft Store version. All users need to install it though.

> When a user logs in to the system, or when that user is switched to using fast user switching,
> Backup current brightness level

The said function will do it.

> Apply the previous brightness level for this specific user
> Apply the original brightness level that was backed up.

It cannot be done reliably because this app will not given a time to change the brightness at such times.

**Comment by BartTK** [comment]
Using that setting and installing it for all users is not perfect, but good enough for me. Thanks!
