### ISSUE TITLE
Apple Cinema display is no longer detected by Monitorian

### ISSUE THREAD

**Issue by Soggy-Pancake** [emoacht/Monitorian#484]
Apple LED Cinema display is no longer showing up in monotorian and I can't change its brightness any other way

GPU: NVidia GTX 1080   -> Displayport
WIndows 10

**Comment by emoacht** [comment]
Please read [Reporting](https://github.com/emoacht/Monitorian#reporting)

**Comment by Soggy-Pancake** [comment]
Here is probe.log while I wait for it to let me save operations 
[probe.log](https://github.com/emoacht/Monitorian/files/12036900/probe.log)

**Comment by emoacht** [comment]
Thanks for the logs.
Looking at probe.log, I found that the capabilities string from Apple Cinema Display uses upper-cased "VCP" instead of normal lower-cased "vcp". I have never seen capitarized "VCP" from other monitors. 
So, that displaly could be detected before? You updated its firmware recently? If you have another Apple monitor, could you post their porbe.log as well?

**Comment by Soggy-Pancake** [comment]
I only have the one but it was detected before a few months back and responded correctly. Changing brightness values worked as expected

**Comment by emoacht** [comment]
Thanks for the information.
I identified one of the changes in ee570b59394a37fe8bd57850bd6a0cb85d97704d causes this issue. I will revert the change.

**Comment by emoacht** [comment]
Fixed by f80b0042a95e94f831f4125e9c8872ce996f3f28
