### ISSUE TITLE
[SUG] Transparent App Icon

### ISSUE THREAD

**Issue by soyfrien** [emoacht/Monitorian#535]
The current app icon will only look transparent in environments using the same background color, in others it will look something like this:
<img width="67" alt="App Icon without transparent background showing mismatch" src="https://github.com/emoacht/Monitorian/assets/3385925/f59d9a4b-d56a-41f0-bab3-a674af4f3977">
_Background color mismatch._

Here is a copy with a transparent bg that should blend in a little better:
![monitorian-icon ico](https://github.com/emoacht/Monitorian/assets/3385925/138f4840-3e58-439a-b0f8-0f2b2dc94712)
_Removing the .png extension will show this is actually an .ico file. It has been renamed to a format allowed by the Issues editor._

**Comment by soyfrien** [comment]
Actually, don't use that file. It doesn't look quite right when I tested it out from Visual Studio:
![monitorian-icon-issue](https://github.com/emoacht/Monitorian/assets/3385925/494d575d-8560-4b8f-ae93-097dcabb5057)
_Something is wrong with the diagonal lines on the right._

But it'd still be nice if someone can make this suggestion happen, so I'll leave this open.

**Comment by emoacht** [comment]
Which icon you are talking about? Please be specific.

**Comment by soyfrien** [comment]
Source/Monitorian/Resources/Icons/AppIcon.ico

**Comment by emoacht** [comment]
I mean the icon shown in which context.

**Comment by soyfrien** [comment]
Ahh, I noticed it from the Start menu. The GIF is an example of the app being pinned to Start in Windows 11, but it can also be seen if scrolling through **All apps**.

Here's a screenshot with a blue background:
<img width="540" alt="image" src="https://github.com/emoacht/Monitorian/assets/3385925/96137eea-ebbf-4c39-b636-2752242cc89c">
The Monitorian icon on the left is the one with a transparent background, and the one on the right is the one currently being used.

**Comment by emoacht** [comment]
Thank you for explanation.

The app icon is intentionally given dark, black background so that it would be visible against light, white background such as Start menu (of light theme), Desktop (when the wallpaper is of light color) and Explorer (Windows 10, or Windows 11 of light theme).

Having said that, in the case of Microsoft Store version and the icon shown in Start menu, it seems not impossible to switch the icon images depending on current theme. See [Construct your Windows app's icon](https://learn.microsoft.com/en-us/windows/apps/design/style/iconography/app-icon-construction#icon-sizes-wpf-uwp-winui). However, it will require to prepare several sets of images in different sizes and darl/light theme.

Honestry speakings, I don't have strong interest in working on this preparation just for transparency.

**Comment by emoacht** [comment]
Thank you for explanation.

The app icon is intentionally given dark, black background so that it would be visible against light, white background such as Start menu (of light theme), Desktop (when the wallpaper is of light color) and Explorer (Windows 10, or Windows 11 of light theme).

Having said that, in the case of Microsoft Store version and the icon shown in Start menu, it seems not impossible to switch the icon images depending on current theme. See [Construct your Windows app's icon](https://learn.microsoft.com/en-us/windows/apps/design/style/iconography/app-icon-construction#complete-list-of-icons-and-variations). However, it will require to prepare several sets of images in different sizes and dark/light theme.

Honestry speakings, I don't have strong interest in working on this preparation just for transparency.

**Comment by soyfrien** [comment]
I didn't think about having to go through the store to update it, that's a good point. Thank you for the information on how to do it. Maybe it would be worth it if someone could create them in advance for you. I was unable to do it with Paint.NET using the originals as a source without losing too much detail in the shadows.

Anyway, I love the app as it is.
