### ISSUE TITLE
[Feature Request] Completely Turn Off Display

### ISSUE THREAD

**Issue by KrisCris** [emoacht/Monitorian#541]
Thanks for creating this awesome tool!

My laptop display lights even with the brightness set to 0, so I am looking for a way to turn it off.

**Comment by emoacht** [comment]
AFAIK, powering off laptop's internal display is not possible except when the user sets Multiple displays' settings in the OS's Display settings so that the desktop is only shown on the other (external) displays. And this settings is persistent unless the user intentionally changes it again in the OS's Display settings.

So it would not be accomplished easily and there is no plan to do so..

**Comment by emoacht** [comment]
AFAIK, powering off laptop's internal display is not possible except when the user sets Multiple displays' settings in the OS's Display settings to make the desktop being only shown on the other (external) displays. And this settings is persistent unless the user intentionally changes it again in the OS's Display settings.

So it would not be accomplished easily and there is no plan to implement it.
