### ISSUE TITLE
Offset control and auto brightness 

### ISSUE THREAD

**Issue by Hanguk66** [emoacht/Monitorian#568]
The brightness on my desktop monitor still differs from that of my notebook's monitor, even though they are synchronized. Can you add an offset control for each brightness control when they are synchronized?

Additionally, is there a way for the monitor to utilize the brightness sensor of my notebook, even though the content is only being displayed on my desktop monitor while the notebook monitor is turned off?

**Comment by emoacht** [comment]
As for the first point, change the adjustable range of monitors so that the actual brightness of both monitors match at the same brightness value. Please read https://github.com/emoacht/Monitorian/issues/427#issuecomment-1480316139

As for the seond point, the matters around ambient light sensor are not so simple.
