### ISSUE TITLE
Contrast option not working properly with DisplayPort

### ISSUE THREAD

**Issue by McWally** [emoacht/Monitorian#600]
When connecting the monitor via DisplayPort, the brightness works, but contrast doesn't.
If I switch to HDMI then DisplayPort again, it fixes sometimes.
Also, if I turn the monitor off then on, first it may bug and not let u control anything (that's normal ig), after some seconds or another off/on it works for brightness, but contrast fails more times.

**Comment by emoacht** [comment]
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__? How to produce the log is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme.

**Comment by McWally** [comment]
[probe.log](https://github.com/user-attachments/files/15847663/probe.log)

With both HDMI and DP at the same time, for HDMI I can change contrast, it's also marked as "true" on the log, not with DP. But sometimes with DP when removing HDMI somehow detects contrast. Still when I reboot pc or monitor, 90% of the time contrast setting is lost.

**Comment by emoacht** [comment]
Thank you for the log.
The monitors model seem to support DDC/CI but you have bad connections. I would suggest you to change the connections.
Also, you can try `/preclear` option so that this app treats them as if they support contrast . See https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584
It may or may not solve the issue.

**Comment by AdriOnti** [comment]
Hey! Thanks for your help, still doesn't work, I executed monitorian /preclear "(the id)"  on the CMD.

It seems it did something since it opened monitorian when executed, but still couldn't change the contrast.

I tried executing it from the hidden menu aswell. But I couldn't find a way to execute that prompt. Wrote the prompt but tried different buttons to execute and it didn't seem to do anything. 

Is there another way to make monitorian think it has enabled contrast? And hopefully the contrast bar works. 

Also, does it make any sense for u that when I connect HDMI and then go back to DP sometimes the contrast setting stays fixed? 

Sorry for bothering and thanks for replying that fast

**Comment by emoacht** [comment]
If you run this app with `/preclear` and it doesn't make a difference, it means your monitor does not respond to the command sent by this app.
To be  clear, this is a hardware issue and unless your monitors respond as expected, nothing this app can do.
