### ISSUE TITLE
[BUG] One random Display of a Group changes it's relative Brightness every now and then

### ISSUE THREAD

**Issue by boop5** [emoacht/Monitorian#93]
I have 3 Displays. All of them are grouped at the same % of brightness. So what I do is I ungroup them all, put them at 0% and group them together. Now I move the slider around and all displays have the same brightness.

Every now and then of the Displays changes the Brightness %. Only in the menu, not in reality. So I have to ungroup/regroup them again to get them all at the same Brightness.

I usually put my computer to hibernate and t might have something todo with it. I'm not sure at this point I'll keep an eye on it.

Here is an image explaining the situation. 

![image](https://user-images.githubusercontent.com/4655466/95194446-925e1580-07d5-11eb-8b57-bc762d2d77b4.png)

**Comment by emoacht** [comment]
Thank you for reporting.
It happens when one of monitors in unison is too slow to respond to the DDC/CI command and left behind. It is a kind of feedback loop and the brightness shown in this app can be dragged by such dull response of monitor.
If you want to look into what really happens, operation.log might be helpful.
